language: python
services:
  - docker
name: "Python 3.7.1 on Xenial Linux"
python: 3.7           
dist: xenial          # required for Python >= 3.7
sudo: required

before_install:
  - sudo apt purge docker-ce
  - curl -fsSL https://get.docker.com/ -o docker-install.sh
  - CHANNEL=nightly sh docker-install.sh
  - sudo docker run --privileged linuxkit/binfmt:v0.7
  - docker buildx create --name mybuilder
  - docker buildx use mybuilder
  - docker buildx inspect --bootstrap

install: 
  - pip3 install --upgrade pip 

jobs:
  include:
    - stage: lint
      name: 'lint'
      script: 
        - pip3 install .
        - pip3 install pylint
        - pylint -rn --errors-only ./magic
    - stage: test
      name: 'test'
      script:
        - pip3 install .
        - pip3 install coveralls pytest-cov
        - py.test --cov magic
        - coveralls
    - stage: deploy
      # if: branch = master
      name: 'deploy agent'
      script:
        - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file Dockerfile.agent.base -t agent-base . --load
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file Dockerfile.agent.simple -t domathologram/test_autobuild:gateway . --push
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file Dockerfile.agent.simple --build-arg AGENT_TYPE=payment -t domathologram/test_autobuild:payments . --push
      
    - script:
        - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file Dockerfile.radius -t domathologram/test_autobuild:radius . --push
      name: 'deploy radius'

    - script:
        - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file Dockerfile.alpine.radius -t domathologram/test_autobuild:radius-alpine . --push
      name: 'deploy alpine radius'

env:
  global:
    - DOCKER_BUILDKIT=1
    - DOCKER_CLI_EXPERIMENTAL=enabled