language: python
services:
  - docker
name: "Python 3.7.1 on Xenial Linux"
python: 3.7           
dist: xenial          # required for Python >= 3.7
sudo: required

before_install:
  - sudo apt purge docker-ce docker-ce-cli
  - curl -fsSL https://get.docker.com/ -o docker-install.sh
  - CHANNEL=nightly sh docker-install.sh

install: 
  - pip3 install --upgrade pip 
  - pip3 install pylint
  - pip3 install .

jobs:
  include:
    - stage: lint
      name: 'lint'
      script: 
        - pylint -rn --errors-only ./magic
    - stage: test
      name: 'test'
      script:
        - pytest
    - stage: deploy
      name: 'deploy'
      script:
        - docker buildx create --name agent
        - docker buildx use agent
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t magicnetwork/latest . --push
