language: python
services:
  - docker
name: "Python 3.7.1 on Xenial Linux"
python: 3.7           
dist: xenial          # required for Python >= 3.7
sudo: required

before_install:
  - docker --version
  - sudo apt purge docker-ce
  - curl -fsSL https://get.docker.com/ -o docker-install.sh
  - CHANNEL=nightly sh docker-install.sh
  - docker --version

install: 
  - pip3 install --upgrade pip 
  - pip3 install pylint
  - pip3 install pytest
  - pip3 install .

jobs:
  include:
    - stage: lint
      name: 'lint'
      script: 
        - pylint -rn --errors-only ./magic
    - stage: test
      name: 'test'
      script:
        - pytest
    - stage: deploy
      name: 'deploy'
      script:
        - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
        - docker buildx create --name magic-agent
        - docker buildx use magic-agent
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file Dockerfile.agent -t domathologram/test_autobuild:latest . --push
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file Dockerfile.agent -t domathologram/test_autobuild:gateway . --push
        - docker buildx build --build-arg AGENT_TYPE=payment --platform linux/amd64,linux/arm64,linux/arm/v7 --file Dockerfile.agent -t domathologram/test_autobuild:payments . --push
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file Dockerfile.radius -t domathologram/test_autobuild:radius . --push
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file Dockerfile.alpine.radius -t domathologram/test_autobuild:radius-alpine . --push

env:
  global:
    - DOCKER_BUILDKIT=1
    - DOCKER_CLI_EXPERIMENTAL=enabled