version: '3'

services:
  sut:
    build: 
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - lint
      - test

  lint:
    build: 
      context: .
      dockerfile: Dockerfile.test
    command: pylint -rn --errors-only ./magic

  test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    command: pytest
